// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB58h9faWYk1m1Mb_o3Rk-4Es9L6rtEi8Q',
    appId: '1:930278399511:web:ede3a911715f8e23f2c652',
    messagingSenderId: '930278399511',
    projectId: 'cart-8d809',
    authDomain: 'cart-8d809.firebaseapp.com',
    databaseURL: 'https://cart-8d809-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cart-8d809.appspot.com',
    measurementId: 'G-K7RBXMVNGV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVho1HjlI--XEraEJoicZif249iMAkLaM',
    appId: '1:930278399511:android:986555d29bfbd8b7f2c652',
    messagingSenderId: '930278399511',
    projectId: 'cart-8d809',
    databaseURL: 'https://cart-8d809-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cart-8d809.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3rBwjMmD2xYhU-vcc5DEpE3tya8FhxDU',
    appId: '1:930278399511:ios:a27e95e67f269839f2c652',
    messagingSenderId: '930278399511',
    projectId: 'cart-8d809',
    databaseURL: 'https://cart-8d809-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cart-8d809.appspot.com',
    iosClientId: '930278399511-lll07eioqok6cv535niqm75ikggn5ugr.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3rBwjMmD2xYhU-vcc5DEpE3tya8FhxDU',
    appId: '1:930278399511:ios:62ea1c9685dd03a6f2c652',
    messagingSenderId: '930278399511',
    projectId: 'cart-8d809',
    databaseURL: 'https://cart-8d809-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cart-8d809.appspot.com',
    iosClientId: '930278399511-bvnq69nd4hdpgihe4e5sn7ji06s44n55.apps.googleusercontent.com',
    iosBundleId: 'com.example.app.RunnerTests',
  );
}
